### PR TITLE
fixes issue #244: Removed duplicate entries and replaces 0xXXX with valid random hex codes

### PR DESCRIPTION
**Pull request by SoarinSkySagar**
This Pull Request is for resolving issue #244. There are no more issues regarding the invalid hex codes now. Here's the checklist for the PR:

- [x] Fix issues such as the "[rhino]" or "[pyramid]" categories which are present twice
- [x] Replace template Hex values such as "0xXXXXXXXXXXXX" which are not numbers as it's only composed of "XXX..." by random Hex values such as "0xFFFFF"
- [x] Check there are no other parsing errors

This PR has been done as part of OnlyDust's ODHack 7.0.

### CODE REVIEW

**Comment by SoarinSkySagar** [comment]
Hi @Marchand-Nicolas , I was assigned the issue for OnlyDust's ODHack 7.0, and here is the PR resolving that issue. Please review and merge or request the required changes if required.

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Hello, thanks for your PR. This is almost perfect! Just needs one little change.

There is still one last compilation error here
```toml
[quest_boost]
private_key = "xxxxxx"
```

This specific private_key needs to be an hex number, such as "0xFFFFFFFFFFFF".
After that we can merge :)

**Comment by SoarinSkySagar** [comment]
GM @Marchand-Nicolas, thanks for pointing it out! I have fixed it now, can you check it?

**Review by Marchand-Nicolas — APPROVED** [review]
Thanks! Lgtml!

**Pull request merged**
