### PR TITLE
Add All Contributors bot back-end

### LINKED ISSUE #278: Add All Contributors bot back-end
## Description

We want to recognize all contributors to this project using the All Contributors bot. This will automate the process of adding contributors to our README.md file.

## Tasks
- [x] 1. Add the All Contributors bot to the repository
- [ ] 2. Set up the initial configuration
- [ ] 3. Update the README.md file with the contributors section
- [ ] 4. Document the process for contributors to add themselves

## Implementation Details

1. Create a `.all-contributorsrc` file in the root of the repository with the following content:

```json
{
  "files": ["README.md"],
  "imageSize": 100,
  "commit": false,
  "contributors": [],
  "contributorsPerLine": 7,
  "projectName": "Starknet Quest",
  "projectOwner": "lfglabs-dev",
  "repoType": "github",
  "repoHost": "https://github.com",
  "skipCi": true,
  "commitConvention": "none"
}
```
2. Add the following section to your README.md file:

```md
Contributors ✨
Thanks goes to these wonderful people 1:
<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore-start -->
<!-- markdownlint-disable -->
<!-- markdownlint-restore -->
<!-- prettier-ignore-end -->
<!-- ALL-CONTRIBUTORS-LIST:END -->
This project follows the all-contributors specification. Contributions of any kind welcome!
```
3. Add instructions for contributors in the README.md file:

```md
## Adding yourself as a contributor

If you've contributed to this project, you can easily add yourself to the contributors list by commenting on any issue or pull request with: `@all-contributors please add <your-github-username> for <contribution-type>`

For example: `@all-contributors please add @fricoben for code, business, and ideas`
 
For a full list of contribution types, check out the [emoji key](https://allcontributors.org/docs/en/emoji-key).
```

After implementing these changes, the All Contributors bot will be set up and ready to use in our repository you can test to add yourself as a contributor

### PR DESCRIPTION
**Pull request by Gerson2102**
Adding all-contributorsrc bot. Resolves #278.

### CODE REVIEW

**Comment by Gerson2102** [comment]
@all-contributors please add @Gerson2102 for code, business, and ideas

**Comment by fricoben** [comment]
@all-contributors please add @irisdv for code

@all-contributors please add @fricoben for code, business and ideas

@all-contributors please add @Th0rgal  for code, business and ideas

@all-contributors please add @Marchand-Nicolas  for code

**Review by fricoben — CHANGES_REQUESTED** [review]
To test I approved the bot PR and it works ! Now you just have to rebase and i'll merge

**Comment by fricoben** [comment]
@all-contributors please add @fricoben for code, business and ideas

**Comment by fricoben** [comment]
@all-contributors please add @Th0rgal for code, business and ideas

**Comment by fricoben** [comment]
@Marchand-Nicolas please add @Marchand-Nicolas for code, business and ideas

**Comment by Marchand-Nicolas** [comment]
Please fix conflicts @Gerson2102

**Comment by Marchand-Nicolas** [comment]
@all-contributors please add @Marchand-Nicolas for code, business and ideas

**Comment by Gerson2102** [comment]
Branch rebased mates! @fricoben @Marchand-Nicolas

**Review by Marchand-Nicolas — APPROVED** [review]
Lgtm!

**Pull request merged**
