### PR TITLE
created advanced contract task type

### LINKED ISSUE #265: Advanced `contract` task type
## Description

Advanced `contract` task type: the aim of this PR is to add a new `verify_contract` route in `src\endpoints\quests`.

## PROPOSED TODO

- [ ] Add the `calls` optional field to the `QuestTaskDocument` type in `src\models.rs` if it is not already present. This is an array of `Call`. Each `Call` is an object with the following fields: `contract` (**string**), `call_data` (**string array**), `entry_point` (**string**), `regex` (**string**). If it doesn't already exist, I suggest you to create a `Call` type that you can then use to type the `Calls` field.
- [ ] Reuse the code from the `verify_balance` route.
- [ ] After each call, check the output using the `regex` field corresponding to field.

### PR DESCRIPTION
**Pull request by Ugo-X**
closes #265 

- [x] Add the calls optional field to the QuestTaskDocument type in src\models.rs if it is not already present. This is an array of Call. Each Call is an object with the following fields: contract (string), call_data (string array), entry_point (string), regex (string). If it doesn't already exist, I suggest you to create a Call type that you can then use to type the Calls field.
 - [x] Reuse the code from the verify_balance route.
 - [x] After each call, check the output using the regex field corresponding to field.

### CODE REVIEW

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
You forgot to update mod.rs at src\endpoints\quests\mod.rs

**Comment by Marchand-Nicolas** [comment]
Also there are several errors in verify_contract due to non existing import. You can implement the missing types

**Comment by Ugo-X** [comment]
Just fixed those chief. its funny cos i already did it all in one go but apparently my auto save was turned off and i didnt notice it .... hahaha

**Review by Marchand-Nicolas — APPROVED** [review]
Tested the whole process, and this is working perfectly! So GG, this wasn't an easy issue!

**Pull request merged**
